# Generated by Django 5.0.14 on 2025-12-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('endereco_completo', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Tomador (Cliente)',
                'verbose_name_plural': 'Tomadores (Clientes)',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_municipal', models.CharField(max_length=20, verbose_name='Inscrição Municipal')),
                ('certificado_a1', models.FileField(upload_to='certificados/', verbose_name='Certificado Digital A1 (.pfx)')),
                ('senha_certificado', models.CharField(max_length=100, verbose_name='Senha do Certificado')),
                ('ambiente', models.IntegerField(choices=[(1, 'Produção'), (2, 'Homologação')], default=2, verbose_name='Ambiente')),
            ],
            options={
                'verbose_name': 'Empresa Emissora',
                'verbose_name_plural': 'Empresas Emissoras',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tributacao_nacional', models.CharField(help_text='Ex: 1.07.01', max_length=20, verbose_name='Código Tributação Nacional')),
                ('item_nbs', models.CharField(blank=True, max_length=20, null=True, verbose_name='Item NBS')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota ISS (%)')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço NFS-e',
                'verbose_name_plural': 'Serviços NFS-e',
            },
        ),
        migrations.CreateModel(
            name='NFSe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dps', models.IntegerField(editable=False, verbose_name='Número DPS')),
                ('serie_dps', models.CharField(default='1', max_length=5, verbose_name='Série DPS')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Autorizada', 'Autorizada'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=20, verbose_name='Status')),
                ('chave_acesso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave de Acesso')),
                ('xml_envio', models.TextField(blank=True, null=True, verbose_name='XML Envio')),
                ('xml_retorno', models.TextField(blank=True, null=True, verbose_name='XML Retorno')),
                ('json_erro', models.JSONField(blank=True, null=True, verbose_name='JSON Erro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfse_nacional.cliente', verbose_name='Tomador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfse_nacional.empresa', verbose_name='Empresa Emissora')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nfse_nacional.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'NFS-e Nacional',
                'verbose_name_plural': 'NFS-e Nacional',
                'unique_together': {('empresa', 'serie_dps', 'numero_dps')},
            },
        ),
    ]
