# Generated by Django 5.0.14 on 2025-12-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_responsible_cpf_person_responsible_name'),
        ('nfse_nacional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfse',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Tomador'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
