# Generated by Django 5.0.14 on 2025-12-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_aliquota_iss_and_more'),
        ('nfse_nacional', '0002_alter_nfse_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfse',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.service', verbose_name='Serviço'),
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
