# Generated by Django 5.0.14 on 2025-12-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0003_alter_nfse_servico_delete_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_mun_ibge',
            field=models.CharField(default='2611606', help_text='Ex: 2611606 (Recife)', max_length=7, verbose_name='Código Município IBGE'),
        ),
    ]
