# Generated by Django 5.1.5 on 2026-02-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0004_empresa_codigo_mun_ibge'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfse',
            name='descricao_servico',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço (Override)'),
        ),
        migrations.AddField(
            model_name='nfse',
            name='valor_servico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Serviço (Override)'),
        ),
    ]
