# Generated by Django 5.1.5 on 2026-02-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0005_nfse_descricao_servico_nfse_valor_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo do Certificado (Base64)'),
        ),
    ]
