# Generated by Django 5.1.5 on 2026-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0006_empresa_certificado_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='serie_padrao',
            field=models.CharField(default='1', max_length=5, verbose_name='Série Padrão'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ultimo_numero_dps',
            field=models.IntegerField(default=0, verbose_name='Último Número DPS Emitido'),
        ),
    ]
