# Generated by Django 5.1.5 on 2026-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0007_empresa_serie_padrao_empresa_ultimo_numero_dps'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfse',
            name='link_danfse',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link DANFSe Portal'),
        ),
        migrations.AddField(
            model_name='nfse',
            name='pdf_danfse',
            field=models.BinaryField(blank=True, null=True, verbose_name='PDF DANFSe'),
        ),
    ]
