# Generated by Django 5.1.5 on 2026-02-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0008_add_pdf_danfse_link_danfse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfse',
            name='inf_adic',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Complementares'),
        ),
    ]
