# Generated by Django 5.0.14 on 2025-11-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Estoque Atual')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3, verbose_name='Tipo de Movimentação')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='estoque.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
            },
        ),
    ]
