# Generated by Django 5.1.5 on 2026-02-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_stocklocation_inventory_inventoryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Família')),
            ],
            options={
                'verbose_name': 'Família de Produto',
                'verbose_name_plural': 'Famílias de Produtos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allow_negative_stock',
            field=models.BooleanField(default=True, verbose_name='Permite Estoque Negativo'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_rented',
            field=models.BooleanField(default=True, verbose_name='Pode ser Locado'),
        ),
        migrations.AddField(
            model_name='product',
            name='cest',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem do Produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno'),
        ),
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_origin',
            field=models.CharField(choices=[('0', '0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8'), ('1', '1 - Estrangeira - Importação direta, exceto a indicada no código 6'), ('2', '2 - Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7'), ('3', '3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%'), ('4', '4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes'), ('5', '5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%'), ('6', '6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural'), ('7', '7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista da CAMEX e gás natural'), ('8', '8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%')], default='0', max_length=1, verbose_name='Origem do Produto'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU / Código'),
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.productfamily', verbose_name='Família'),
        ),
    ]
