# Generated by Django 5.0.14 on 2025-12-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_final_consumer',
            field=models.BooleanField(default=False, verbose_name='Consumidor Final?'),
        ),
    ]
