# Generated by Django 5.0.14 on 2025-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_is_final_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='responsible_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AddField(
            model_name='person',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
    ]
