# Generated by Django 5.0.14 on 2025-12-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_responsible_cpf_person_responsible_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='aliquota_iss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota ISS (%)'),
        ),
        migrations.AddField(
            model_name='service',
            name='codigo_tributacao_nacional',
            field=models.CharField(blank=True, help_text='Ex: 1.07.01', max_length=20, null=True, verbose_name='Código Tributação Nacional'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada (NFS-e)'),
        ),
        migrations.AddField(
            model_name='service',
            name='item_nbs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Item NBS'),
        ),
    ]
