# Generated by Django 5.0.14 on 2025-12-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_aliquota_iss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='codigo_nbs',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Código NBS (9 dígitos)'),
        ),
        migrations.AddField(
            model_name='service',
            name='codigo_tributacao_municipal',
            field=models.CharField(blank=True, help_text='Ex: 14.02.01.501', max_length=20, null=True, verbose_name='Código Tributação Municipal'),
        ),
    ]
