# Generated by Django 5.0.14 on 2025-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_codigo_nbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='codigo_municipio_ibge',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Município IBGE'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
    ]
