# Generated by Django 5.1.5 on 2026-02-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='cora_cert_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Cora Certificado (Base64)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='cora_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cora Client ID'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='cora_key_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Cora Chave Privada (Base64)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='cora_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token API Cora (Legado)'),
        ),
    ]
