# Generated by Django 5.1.5 on 2026-02-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companysettings_cora_cert_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='cora_environment',
            field=models.CharField(choices=[('stage', 'Homologação (Stage)'), ('prod', 'Produção')], default='stage', max_length=10, verbose_name='Ambiente Cora'),
        ),
    ]
