# Generated by Django 5.1.5 on 2026-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companysettings_cora_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('body', models.TextField(help_text='Use tags como {cliente}, {valor}, {vencimento}', verbose_name='Corpo do E-mail')),
                ('template_type', models.CharField(choices=[('BOLETO_NF', 'Boleto + NF'), ('BOLETO', 'Apenas Boleto'), ('FATURA', 'Apenas Fatura'), ('COBRANCA', 'Cobrança'), ('ORCAMENTO', 'Orçamento')], default='BOLETO_NF', max_length=20, verbose_name='Tipo de Template')),
            ],
            options={
                'verbose_name': 'Template de E-mail',
                'verbose_name_plural': 'Templates de E-mail',
            },
        ),
    ]
