# Generated by Django 5.0.14 on 2025-11-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_budget_approved_by_operations_contract_budget'),
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='comercial.budget', verbose_name='Orçamento Origem'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('WAITING_MATERIAL', 'Aguardando Material'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
