# Generated by Django 5.0.14 on 2025-11-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('operacional', '0002_serviceorder_budget_alter_serviceorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duração'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='order_type',
            field=models.CharField(choices=[('Preventiva', 'Manutenção Preventiva'), ('Corretiva', 'Manutenção Corretiva'), ('Instalacao', 'Instalação'), ('Outro', 'Outro')], default='Corretiva', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='reason',
            field=models.CharField(choices=[('Solicitacao', 'Solicitação do Cliente'), ('Defeito', 'Defeito Apresentado'), ('Garantia', 'Garantia'), ('Outro', 'Outro')], default='Solicitacao', max_length=50, verbose_name='Motivo da OS'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Atendimento'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='technical_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_collaborator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_team', to='core.person', verbose_name='Equipe Técnica'),
        ),
    ]
