# Generated by Django 5.0.14 on 2025-12-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_stocklocation_inventory_inventoryitem_and_more'),
        ('operacional', '0003_serviceorder_address_serviceorder_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='product',
            field=models.CharField(blank=True, help_text='Produto ou Serviço', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.product', verbose_name='Produto')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operacional.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Item de OS',
                'verbose_name_plural': 'Itens de OS',
            },
        ),
    ]
