# Generated by Django 5.0.14 on 2025-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0004_alter_serviceorder_product_serviceorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Assinatura Cliente'),
        ),
    ]
