# Generated by Django 5.0.14 on 2025-12-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0005_serviceorder_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='checkin_lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Latitude Check-in'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='checkin_long',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='Longitude Check-in'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Check-in'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Check-out'),
        ),
        migrations.CreateModel(
            name='OSAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('file', models.ImageField(upload_to='uploads/os_fotos/%Y/%m/', verbose_name='Foto/Anexo')),
                ('type', models.CharField(choices=[('Antes', 'Antes do Serviço'), ('Depois', 'Depois do Serviço'), ('Diagnostico', 'Diagnóstico/Laudo')], default='Diagnostico', max_length=20, verbose_name='Tipo')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='operacional.serviceorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Anexo de OS',
                'verbose_name_plural': 'Anexos de OS',
            },
        ),
    ]
