# Generated by Django 5.0.14 on 2025-12-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_technician'),
        ('operacional', '0006_serviceorder_checkin_lat_serviceorder_checkin_long_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_technician', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technical_team',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_collaborator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_team', to='core.person', verbose_name='Equipe Técnica (Legado)'),
        ),
    ]
