# Generated by Django 5.0.14 on 2025-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0007_serviceorder_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Solução'),
        ),
    ]
