# Generated by Django 5.0.14 on 2025-12-19 17:05

import django.db.models.deletion
import operacional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0008_serviceorder_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Checklist: Categoria',
                'verbose_name_plural': 'Checklist: Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('texto', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('tipo', models.CharField(choices=[('options', 'Múltipla Escolha (Sim/Não/ND)'), ('text', 'Texto Curto'), ('number', 'Número')], default='options', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='operacional.checklistcategoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Checklist: Pergunta',
                'verbose_name_plural': 'Checklist: Perguntas',
                'ordering': ['categoria__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('resposta_valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resposta')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=operacional.models.checklist_photo_path, verbose_name='Foto')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_respostas', to='operacional.serviceorder', verbose_name='Ordem de Serviço')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.checklistpergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Checklist: Resposta',
                'verbose_name_plural': 'Checklist: Respostas',
                'unique_together': {('os', 'pergunta')},
            },
        ),
    ]
