# Generated by Django 5.1.5 on 2026-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0009_checklistcategoria_checklistpergunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('INSTALLATION_PENDING', 'Instalação Pendente'), ('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('WAITING_MATERIAL', 'Aguardando Material'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
