from django import forms
from .models import Empresa, NFSe

class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = '__all__'
        widgets = {
            'senha_certificado': forms.PasswordInput(),
        }

class NFSeForm(forms.ModelForm):
    class Meta:
        model = NFSe
        fields = ['empresa', 'cliente', 'servico']
        # numero_dps is auto-generated
        # status, data_emissao are automatic
        # xml fields are generated by the backend logic
