# Generated by Django 5.0.14 on 2025-11-26 12:48

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0002_delete_client_delete_supplier'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Faturamento',
                'verbose_name_plural': 'Grupos de Faturamento',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Modelo')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contrato',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Rascunho', max_length=20, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Data')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição/Itens')),
                ('client', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('modality', models.CharField(choices=[('Mensal', 'Mensal'), ('Anual', 'Anual')], default='Mensal', max_length=20, verbose_name='Modalidade')),
                ('due_day', models.IntegerField(verbose_name='Dia de Vencimento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Cancelado', 'Cancelado'), ('Expirado', 'Expirado')], default='Ativo', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Assinatura')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Assinatura')),
                ('billing_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.billinggroup', verbose_name='Grupo de Faturamento')),
                ('client', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Cliente')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.contracttemplate', verbose_name='Modelo de Contrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
