# Generated by Django 5.0.14 on 2025-11-27 20:16

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_initial'),
        ('estoque', '0002_brand_category_product_brand_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Serviço')),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Base')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.RemoveField(
            model_name='budget',
            name='description',
        ),
        migrations.AddField(
            model_name='budget',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='budget',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='budget',
            name='observation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='budget',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='budget',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Ganho', 'Ganho'), ('Perdido', 'Perdido'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido')], default='Aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.CreateModel(
            name='BudgetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='comercial.budget')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.product', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='comercial.budget')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.service', verbose_name='Serviço')),
            ],
        ),
    ]
