# Generated by Django 5.0.14 on 2025-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_service_remove_budget_description_budget_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='followup_strategy',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatico', 'Automático')], default='Manual', max_length=20, verbose_name='Estratégia de Follow-up'),
        ),
        migrations.AddField(
            model_name='budget',
            name='last_followup',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Follow-up'),
        ),
    ]
