# Generated by Django 5.0.14 on 2025-11-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_budget_followup_strategy_budget_last_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='approved_by_operations',
            field=models.BooleanField(default=False, verbose_name='Liberado pelo Operacional'),
        ),
        migrations.AddField(
            model_name='contract',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.budget', verbose_name='Orçamento Origem'),
        ),
    ]
