# Generated by Django 5.0.14 on 2025-12-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_budget_approved_by_operations_contract_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='payment_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes do Pagamento'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão de Crédito'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50, verbose_name='Forma de Pagamento'),
        ),
    ]
