# Generated by Django 5.0.14 on 2025-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_budget_payment_details_alter_budget_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='template_type',
            field=models.CharField(choices=[('Novo Contrato', 'Novo Contrato'), ('Cancelamento', 'Cancelamento'), ('Reajuste', 'Reajuste'), ('Aditivos', 'Aditivos')], default='Novo Contrato', max_length=50, verbose_name='Tipo de Modelo'),
        ),
    ]
