# Generated by Django 5.1.5 on 2026-02-02 23:52

from django.db import migrations


def update_due_days(apps, schema_editor):
    Contract = apps.get_model('comercial', 'Contract')
    Contract.objects.all().update(due_day=14)

class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_contracttemplate_template_type'),
    ]

    operations = [
        migrations.RunPython(update_due_days),
    ]
