# Generated by Django 5.1.5 on 2026-02-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_update_due_day_to_14'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='due_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia de Vencimento Padrão'),
        ),
    ]
