# Generated by Django 5.1.5 on 2026-02-05 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_billinggroup_due_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.CharField(choices=[('MANUTENCAO', 'Manutenção Mensal'), ('MONITORAMENTO', 'Monitoramento'), ('PONTO', 'Ponto Eletrônico'), ('COMODATO', 'Comodato Equipamentos'), ('OUTROS', 'Outros')], default='MANUTENCAO', max_length=20, verbose_name='Categoria')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comercial.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Item de Contrato',
                'verbose_name_plural': 'Itens de Contrato',
            },
        ),
    ]
