# Generated by Django 5.1.5 on 2026-02-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_contractitem'),
        ('financeiro', '0015_seed_dre_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='financial_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira', verbose_name='Categoria Financeira (DRE)'),
        ),
    ]
