# Generated by Django 5.1.5 on 2026-02-08 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_contractitem_financial_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractitem',
            options={},
        ),
        migrations.CreateModel(
            name='ContractReadjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Reajuste')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual (%)')),
                ('status', models.CharField(choices=[('APPLIED', 'Aplicado'), ('CANCELLED', 'Cancelado')], default='APPLIED', max_length=20, verbose_name='Status')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
            ],
            options={
                'verbose_name': 'Reajuste de Contrato',
                'verbose_name_plural': 'Reajustes de Contrato',
            },
        ),
        migrations.CreateModel(
            name='ContractReadjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_snapshot', models.JSONField(help_text='Armazena IDs e valores unitários antigos', verbose_name='Snapshot dos Itens')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.contract')),
                ('readjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='comercial.contractreadjustment')),
            ],
        ),
    ]
