# Generated by Django 5.1.5 on 2026-02-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_alter_contractitem_options_contractreadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='next_readjustment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Reajuste'),
        ),
        migrations.AddField(
            model_name='contractreadjustment',
            name='readjustment_type',
            field=models.CharField(choices=[('READJUSTMENT', 'Reajuste'), ('DEFERRAL', 'Adiamento')], default='READJUSTMENT', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contractreadjustment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual (%)'),
        ),
        migrations.AlterField(
            model_name='contractreadjustment',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Aplicado'), ('CANCELLED', 'Cancelado'), ('DEFERRED', 'Adiado')], default='APPLIED', max_length=20, verbose_name='Status'),
        ),
    ]
