# Generated by Django 5.1.5 on 2026-02-11 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_contract_next_readjustment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AddField(
            model_name='budget',
            name='commission_paid',
            field=models.BooleanField(default=False, verbose_name='Comissão Paga'),
        ),
        migrations.AddField(
            model_name='budget',
            name='gratification_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Gratificação'),
        ),
        migrations.AddField(
            model_name='budget',
            name='origin',
            field=models.CharField(choices=[('direta', 'Demanda Direta (Cliente)'), ('preventiva', 'Demanda de Preventiva')], default='direta', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='budget',
            name='seller_commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão Vendedor (%)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes', to=settings.AUTH_USER_MODEL, verbose_name='Técnico (Indicação)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='technician_commission_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão Técnico (%)'),
        ),
    ]
