# Generated by Django 5.1.5 on 2026-02-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_budget_closing_date_budget_commission_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Serviço')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Serviço de Manutenção',
                'verbose_name_plural': 'Serviços de Manutenção',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='maintenance_services',
            field=models.ManyToManyField(blank=True, to='comercial.maintenanceservice', verbose_name='Serviços de Manutenção Contratados'),
        ),
    ]
