# Generated by Django 5.1.5 on 2026-02-12 22:17

from django.db import migrations


def create_initial_services(apps, schema_editor):
    MaintenanceService = apps.get_model('comercial', 'MaintenanceService')
    services = [
        "Motores portão de veículos",
        "Fechaduras elétrica ou magnéticas",
        "Sistema de câmeras",
        "Controle de acesso de pedestres",
        "Controle de acesso de veículos",
        "Cerce elétrica",
        "Alarme",
        "Antena coletiva",
        "Ponto digital",
        "Torre de Monitoramento",
        "Alarme monitorado",
        "Interfones"
    ]
    for i, name in enumerate(services):
        MaintenanceService.objects.get_or_create(name=name, defaults={'order': i})

class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_maintenanceservice_contract_maintenance_services'),
    ]

    operations = [
        migrations.RunPython(create_initial_services),
    ]
