# Generated by Django 5.0.14 on 2025-11-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Documento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Documento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'is_client': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('type', models.CharField(choices=[('EXPENSE', 'Despesa'), ('REVENUE', 'Receita')], max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={'verbose_name': 'Reconciliação Bancária', 'verbose_name_plural': 'Reconciliações Bancárias'},
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='transaction_type',
            field=models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=10, verbose_name='Tipo de Transação'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'REVENUE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.financialcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.financialcategory', verbose_name='Categoria'),
        ),
    ]
