# Generated by Django 5.0.14 on 2025-11-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_accountpayable_accountreceivable_financialcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Conta')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Conta')),
                ('agency', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
            ],
            options={
                'verbose_name': 'Conta Caixa',
                'verbose_name_plural': 'Contas Caixa',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Centro de Resultado',
                'verbose_name_plural': 'Centros de Resultado',
            },
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='occurrence_date',
            field=models.DateField(default='2025-01-01', verbose_name='Data de Ocorrência'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='occurrence_date',
            field=models.DateField(default='2025-01-01', verbose_name='Data de Ocorrência'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.cashaccount', verbose_name='Conta Caixa'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.cashaccount', verbose_name='Conta Caixa'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.costcenter', verbose_name='Centro de Resultado'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.costcenter', verbose_name='Centro de Resultado'),
        ),
    ]
