# Generated by Django 5.0.14 on 2025-11-28 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0003_cashaccount_costcenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('type', models.CharField(choices=[('PAYMENT', 'Pagamento'), ('RECEIPT', 'Recebimento')], default='RECEIPT', max_length=10, verbose_name='Tipo de Lançamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
    ]
