# Generated by Django 5.0.14 on 2025-11-28 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('year', models.IntegerField(unique=True, verbose_name='Ano')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Planejamento Orçamentário',
                'verbose_name_plural': 'Planejamentos Orçamentários',
            },
        ),
        migrations.AddField(
            model_name='financialcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='financeiro.financialcategory', verbose_name='Categoria Pai'),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Planejado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.financialcategory', verbose_name='Categoria')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financeiro.budgetplan', verbose_name='Planejamento')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'unique_together': {('plan', 'category', 'month')},
            },
        ),
    ]
