# Generated by Django 5.0.14 on 2025-12-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_invoice_client_invoice_competence_month_and_more'),
        ('financeiro', '0005_budgetplan_financialcategory_parent_budgetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='faturamento.invoice', verbose_name='Fatura'),
        ),
    ]
