# Generated by Django 5.0.14 on 2025-12-11 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_accountreceivable_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashaccount',
            options={'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Atual'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial'),
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('transaction_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3, verbose_name='Tipo')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financeiro.cashaccount', verbose_name='Conta Bancária')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.financialcategory', verbose_name='Categoria')),
                ('related_payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financeiro.accountpayable', verbose_name='Conta a Pagar Vinculada')),
                ('related_receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financeiro.accountreceivable', verbose_name='Conta a Receber Vinculada')),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
