# Generated by Django 5.0.14 on 2025-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_cashaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpayable',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CARD', 'Cartão'), ('TRANSFER', 'Transferência Bancária'), ('CREDIT', 'Crédito')], max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
