# Generated by Django 5.1.5 on 2026-02-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_alter_accountpayable_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='cora_copy_paste',
            field=models.TextField(blank=True, null=True, verbose_name='Código Pix/Linha Digitável'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='cora_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cora ID'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='cora_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do PDF'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='cora_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Cora'),
        ),
    ]
