# Generated by Django 5.1.5 on 2026-02-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_accountreceivable_cora_copy_paste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreceivable',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência / NF'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa (R$)'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='interest_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros (% ao mês)'),
        ),
    ]
