# Generated by Django 5.1.5 on 2026-02-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_accountreceivable_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='current_installment',
            field=models.IntegerField(default=1, verbose_name='Parcela Atual'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='total_installments',
            field=models.IntegerField(default=1, verbose_name='Total de Parcelas'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='current_installment',
            field=models.IntegerField(default=1, verbose_name='Parcela Atual'),
        ),
        migrations.AddField(
            model_name='accountreceivable',
            name='total_installments',
            field=models.IntegerField(default=1, verbose_name='Total de Parcelas'),
        ),
    ]
