# Generated by Django 5.1.5 on 2026-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_accountpayable_current_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Externo'),
        ),
    ]
