# Generated by Django 5.1.5 on 2026-02-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_financialtransaction_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpayable',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='É Recorrente?'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='recurrence_period',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensal'), ('WEEKLY', 'Semanal'), ('YEARLY', 'Anual')], max_length=10, null=True, verbose_name='Período de Recorrência'),
        ),
    ]
