# Generated by Django 5.1.5 on 2026-02-07 01:22

import django.db.models.deletion
from django.db import migrations, models


def clear_old_references(apps, schema_editor):
    AccountPayable = apps.get_model('financeiro', 'AccountPayable')
    AccountReceivable = apps.get_model('financeiro', 'AccountReceivable')
    BudgetItem = apps.get_model('financeiro', 'BudgetItem')
    FinancialTransaction = apps.get_model('financeiro', 'FinancialTransaction')
    
    AccountPayable.objects.update(category=None, cost_center=None)
    AccountReceivable.objects.update(category=None, cost_center=None)
    BudgetItem.objects.update(category=None)
    FinancialTransaction.objects.update(category=None)

class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_accountpayable_is_recurring_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_old_references),
        migrations.CreateModel(
            name='CentroResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Centro de Resultado',
                'verbose_name_plural': 'Centros de Resultado',
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada/Receita'), ('saida', 'Saída/Despesa')], max_length=10, verbose_name='Tipo')),
                ('grupo_dre', models.CharField(max_length=50, verbose_name='Agrupador para a DRE')),
                ('ordem_exibicao', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='financeiro.categoriafinanceira', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
            },
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'saida'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'entrada'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoriafinanceira', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='accountpayable',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centroresultado', verbose_name='Centro de Resultado'),
        ),
        migrations.AlterField(
            model_name='accountreceivable',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.centroresultado', verbose_name='Centro de Resultado'),
        ),
        migrations.DeleteModel(
            name='FinancialCategory',
        ),
        migrations.DeleteModel(
            name='CostCenter',
        ),
    ]
