# Generated by Django 5.1.5 on 2026-02-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_companysettings_address_companysettings_email_and_more'),
        ('financeiro', '0017_auto_create_transactions_for_baixas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('inscricao_municipal', models.CharField(max_length=20, verbose_name='Inscrição Municipal')),
                ('codigo_municipio_ibge', models.CharField(default='2611606', max_length=7, verbose_name='Código Município IBGE')),
                ('regime_tributario', models.IntegerField(default=1, verbose_name='Regime Tributário')),
                ('ultimo_numero_dps', models.IntegerField(default=0, verbose_name='Último Nº DPS Emitido')),
                ('ultimo_numero_nfse', models.IntegerField(default=0, verbose_name='Último Nº NFS-e Emitida')),
                ('cnae_padrao', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE Padrão')),
                ('codigo_servico_lc116_padrao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Item LC 116 Padrão')),
                ('certificado_a1_base64', models.TextField(blank=True, null=True, verbose_name='Certificado A1 (Base64)')),
                ('senha_certificado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha do Certificado')),
            ],
            options={
                'verbose_name': 'Configuração Fiscal',
                'verbose_name_plural': 'Configurações Fiscais',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_dps', models.IntegerField(unique=True, verbose_name='Nº DPS')),
                ('serie', models.CharField(default='1', max_length=5, verbose_name='Série')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('xml_enviado', models.TextField(blank=True, null=True, verbose_name='XML Enviado')),
                ('xml_retorno', models.TextField(blank=True, null=True, verbose_name='XML Retorno')),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Protocolo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('processando', 'Processando'), ('emitida', 'Emitida'), ('erro', 'Erro')], default='rascunho', max_length=20, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'NFS-e',
                'verbose_name_plural': 'Notas Fiscais de Serviço',
            },
        ),
    ]
