# Generated by Django 5.1.5 on 2026-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_empresafiscal_notafiscalservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresafiscal',
            name='cnae_padrao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE Padrão'),
        ),
        migrations.AddField(
            model_name='empresafiscal',
            name='codigo_servico_lc116_padrao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Item LC 116 Padrão'),
        ),
        migrations.AddField(
            model_name='empresafiscal',
            name='ultimo_numero_dps',
            field=models.IntegerField(default=0, verbose_name='Último Nº DPS Emitido'),
        ),
        migrations.AddField(
            model_name='empresafiscal',
            name='ultimo_numero_nfse',
            field=models.IntegerField(default=0, verbose_name='Último Nº NFS-e Emitida'),
        ),
        migrations.AddField(
            model_name='notafiscalservico',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notafiscalservico',
            name='numero_dps',
            field=models.IntegerField(unique=True, verbose_name='Nº DPS'),
        ),
    ]
