# Generated by Django 5.1.5 on 2026-02-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0011_invoiceitem_financial_category'),
        ('financeiro', '0019_empresafiscal_cnae_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalservico',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfs_record', to='faturamento.invoice', verbose_name='Fatura Vinculada'),
        ),
    ]
