# Generated by Django 5.1.5 on 2026-02-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_notafiscalservico_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venda', models.CharField(max_length=50, verbose_name='Tipo de Venda')),
                ('pct_vendedor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão Vendedor (%)')),
                ('pct_tecnico', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comissão Técnico (%)')),
            ],
            options={
                'verbose_name': 'Configuração de Comissão',
                'verbose_name_plural': 'Configurações de Comissão',
            },
        ),
    ]
