# Generated by Django 5.0.14 on 2025-12-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_contracttemplate_template_type'),
        ('core', '0003_person_responsible_cpf_person_responsible_name'),
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.person', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='competence_month',
            field=models.IntegerField(null=True, verbose_name='Mês de Competência'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='competence_year',
            field=models.IntegerField(null=True, verbose_name='Ano de Competência'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='comercial.contract', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='comercial.billinggroup'),
        ),
    ]
