# Generated by Django 5.0.14 on 2025-12-10 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_person_codigo_municipio_ibge_alter_person_state_and_more'),
        ('estoque', '0003_stocklocation_inventory_inventoryitem_and_more'),
        ('faturamento', '0002_invoice_client_invoice_competence_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44, verbose_name='Chave de Acesso')),
                ('numero_nota', models.CharField(max_length=20, verbose_name='Número da Nota')),
                ('serie', models.CharField(max_length=5, verbose_name='Série')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('arquivo_xml', models.FileField(upload_to='uploads/nfe/', verbose_name='Arquivo XML')),
                ('status', models.CharField(choices=[('IMPORTADA', 'Importada'), ('LANCADA', 'Lançada'), ('CANCELADA', 'Cancelada')], default='IMPORTADA', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
            },
        ),
        migrations.CreateModel(
            name='NotaEntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='faturamento.notaentrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.product', verbose_name='Produto')),
            ],
        ),
    ]
