# Generated by Django 5.0.14 on 2025-12-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_stocklocation_inventory_inventoryitem_and_more'),
        ('faturamento', '0003_notaentrada_notaentradaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaentradaitem',
            name='cEAN',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='EAN no XML'),
        ),
        migrations.AddField(
            model_name='notaentradaitem',
            name='cProd',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Código no XML'),
        ),
        migrations.AddField(
            model_name='notaentradaitem',
            name='xProd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome no XML'),
        ),
        migrations.AlterField(
            model_name='notaentradaitem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estoque.product', verbose_name='Produto'),
        ),
    ]
