# Generated by Django 5.0.14 on 2025-12-11 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_notaentradaitem_cean_notaentradaitem_cprod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaentrada',
            name='chave_acesso',
            field=models.CharField(max_length=44, unique=True, verbose_name='Chave de Acesso'),
        ),
        migrations.CreateModel(
            name='NotaEntradaParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.CharField(max_length=3, verbose_name='Nº Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('BOLETO', 'Boleto Bancário'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('OUTROS', 'Outros')], default='BOLETO', max_length=20, verbose_name='Forma de Pagamento')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='faturamento.notaentrada')),
            ],
        ),
    ]
