# Generated by Django 5.1.5 on 2026-02-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_alter_notaentrada_chave_acesso_notaentradaparcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='boleto_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Boleto'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail enviado em'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nfse_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da NFSe'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_fatura',
            field=models.FileField(blank=True, null=True, upload_to='faturas/pdf/', verbose_name='PDF da Fatura'),
        ),
    ]
