# Generated by Django 5.1.5 on 2026-02-03 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_update_due_day_to_14'),
        ('faturamento', '0006_invoice_boleto_url_invoice_email_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_month', models.IntegerField(verbose_name='Mês de Competência')),
                ('competence_year', models.IntegerField(verbose_name='Ano de Competência')),
                ('day_range_start', models.IntegerField(default=1, verbose_name='Dia Cobrança Início')),
                ('day_range_end', models.IntegerField(default=31, verbose_name='Dia Cobrança Fim')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('status', models.CharField(choices=[('PROCESSING', 'Em Processamento'), ('COMPLETED', 'Concluído'), ('ERROR', 'Erro')], default='PROCESSING', max_length=20, verbose_name='Status')),
                ('total_contracts', models.IntegerField(default=0, verbose_name='Total de Contratos')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Faturado')),
                ('total_not_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Não Faturado')),
                ('billing_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.billinggroup', verbose_name='Grupo de Faturamento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Lote de Faturamento',
                'verbose_name_plural': 'Lotes de Faturamento',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='faturamento.billingbatch', verbose_name='Lote de Faturamento'),
        ),
    ]
