# Generated by Django 5.1.5 on 2026-02-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0007_billing_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição/Produto/Serviço')),
                ('item_type', models.CharField(choices=[('SERVICE', 'Serviço'), ('PRODUCT', 'Produto')], default='SERVICE', max_length=10, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações/Referência')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faturamento.invoice', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
            },
        ),
    ]
