# Generated by Django 5.1.5 on 2026-02-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0008_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CARD', 'Cartão'), ('TRANSFER', 'Transferência Bancária'), ('OUTRO', 'Outro')], default='BOLETO', max_length=50, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
