# Generated by Django 5.1.5 on 2026-02-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0009_invoice_payment_method_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=15, verbose_name='Status do E-mail'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nfse_status',
            field=models.CharField(choices=[('NAO_EMITIDA', 'Não Emitida'), ('PROCESSANDO', 'Processando'), ('EMITIDA', 'Emitida'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='NAO_EMITIDA', max_length=15, verbose_name='Status da NFSe'),
        ),
    ]
