# Generated by Django 5.1.5 on 2026-02-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0011_invoiceitem_financial_category'),
        ('nfse_nacional', '0006_empresa_certificado_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nfse_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_linked', to='nfse_nacional.nfse', verbose_name='Registro NFSe Nacional'),
        ),
    ]
