# Generated by Django 5.1.5 on 2026-02-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0012_invoice_nfse_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='complementary_info',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Complementares'),
        ),
    ]
