# Generated by Django 5.1.5 on 2026-02-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('error', 'Erro'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('inserted_rows', models.IntegerField(default=0)),
                ('updated_rows', models.IntegerField(default=0)),
                ('errors_log', models.JSONField(blank=True, default=list, null=True)),
                ('warnings_log', models.JSONField(blank=True, default=list, null=True)),
                ('validation_results', models.JSONField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dry_run', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Job de Importação',
                'verbose_name_plural': 'Jobs de Importação',
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('module_type', models.CharField(db_index=True, max_length=50)),
                ('file_type', models.CharField(default='xlsx', max_length=10)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('encoding', models.CharField(default='utf-8', max_length=20)),
                ('skip_rows', models.IntegerField(default=0)),
                ('header_row', models.IntegerField(default=0)),
                ('mapping', models.JSONField()),
                ('column_types', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Importação',
                'verbose_name_plural': 'Templates de Importação',
            },
        ),
        migrations.CreateModel(
            name='ModuleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(db_index=True, max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('validation_rules', models.JSONField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campo do Módulo',
                'verbose_name_plural': 'Campos do Módulo',
                'ordering': ['module_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('column_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField()),
                ('original_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='importador.importjob')),
            ],
            options={
                'verbose_name': 'Erro de Importação',
                'verbose_name_plural': 'Erros de Importação',
            },
        ),
        migrations.AddField(
            model_name='importjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='importador.importtemplate'),
        ),
    ]
