# Generated by Django 5.0.14 on 2025-12-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_person_codigo_municipio_ibge_alter_person_state_and_more'),
        ('nfse_nacional', '0004_empresa_codigo_mun_ibge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expira em')),
                ('ambiente', models.IntegerField(choices=[(1, 'Produção'), (2, 'Homologação')], default=2, verbose_name='Ambiente')),
            ],
            options={
                'verbose_name': 'Configuração Cora',
                'verbose_name_plural': 'Configuração Cora',
            },
        ),
        migrations.CreateModel(
            name='BoletoCora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cora_id', models.CharField(max_length=100, unique=True, verbose_name='ID Cora')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado'), ('Atrasado', 'Atrasado')], default='Aberto', max_length=20, verbose_name='Status')),
                ('linha_digitavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linha Digitável')),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Barras')),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do PDF')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_cora', to='core.person', verbose_name='Cliente')),
                ('nfse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_cora', to='nfse_nacional.nfse', verbose_name='NFS-e')),
            ],
            options={
                'verbose_name': 'Boleto Cora',
                'verbose_name_plural': 'Boletos Cora',
            },
        ),
    ]
