# Generated by Django 5.0.14 on 2025-12-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_cora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coraconfig',
            name='certificado_pem',
            field=models.FileField(blank=True, null=True, upload_to='cora_certs/', verbose_name='Certificado PEM'),
        ),
        migrations.AddField(
            model_name='coraconfig',
            name='chave_privada',
            field=models.FileField(blank=True, null=True, upload_to='cora_certs/', verbose_name='Chave Privada'),
        ),
    ]
