# Generated by Django 5.0.14 on 2025-12-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_cora', '0002_coraconfig_certificado_pem_coraconfig_chave_privada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coraconfig',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret'),
        ),
    ]
