# Generated by Django 5.1.5 on 2026-02-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_cora', '0003_alter_coraconfig_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='coraconfig',
            name='dias_protesto',
            field=models.IntegerField(default=0, help_text='Dias após vencimento para protesto (0 = sem protesto)', verbose_name='Dias para Protesto'),
        ),
        migrations.AddField(
            model_name='coraconfig',
            name='instrucoes_boleto',
            field=models.TextField(blank=True, default='Pagável em qualquer banco até o vencimento.\nApós o vencimento cobrar multa e juros.', help_text='Instruções que aparecerão no boleto para o pagador', null=True, verbose_name='Instruções do Boleto'),
        ),
        migrations.AddField(
            model_name='coraconfig',
            name='taxa_juros',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Percentual de juros ao mês (ex: 1.00 para 1% a.m.)', max_digits=5, verbose_name='Taxa de Juros (% a.m.)'),
        ),
        migrations.AddField(
            model_name='coraconfig',
            name='taxa_multa',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Percentual de multa por atraso (ex: 2.00 para 2%)', max_digits=5, verbose_name='Taxa de Multa (%)'),
        ),
    ]
