# Generated by Django 5.1.5 on 2026-02-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_cora', '0004_add_boleto_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coraconfig',
            name='certificado_pem_b64',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Certificado (B64)'),
        ),
        migrations.AddField(
            model_name='coraconfig',
            name='chave_privada_b64',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Chave (B64)'),
        ),
    ]
