# Generated by Django 5.1.5 on 2026-02-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0007_billing_batch'),
        ('integracao_cora', '0005_coraconfig_certificado_pem_b64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletocora',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_cora', to='faturamento.invoice', verbose_name='Fatura Avulsa'),
        ),
    ]
